"""
seed_chemicals.py — ToxiScan Phase 1
Run this script to seed MongoDB with the full harmful chemicals list.

Usage:
    cd backend
    pip install motor python-dotenv
    python seed_chemicals.py

Make sure .env has MONGODB_URI set.
"""

import asyncio
from datetime import datetime
from dotenv import load_dotenv
import os
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv()

# ─────────────────────────────────────────────
# FULL CHEMICALS SEED DATA
# ─────────────────────────────────────────────

CHEMICALS = [

    # ── 1. FORMALDEHYDE ──────────────────────────────────────────────────
    {
        "name": "Formaldehyde",
        "aliases": ["formalin", "methanal", "formic aldehyde", "methylene oxide", "oxomethane"],
        "category": "Formaldehyde",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Known human carcinogen (IARC Group 1). Causes skin irritation, allergic contact dermatitis, and is linked to leukemia and nasopharyngeal cancer with prolonged exposure.",
        "research_url": "https://www.iarc.who.int/wp-content/uploads/2018/07/pr153_E.pdf",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 2. FORMALDEHYDE RELEASERS ─────────────────────────────────────────
    {
        "name": "DMDM Hydantoin",
        "aliases": ["dmdm hydantoin", "1,3-bis(hydroxymethyl)-5,5-dimethylhydantoin", "dimethylol dimethyl hydantoin"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Preservative that slowly releases formaldehyde over time. Linked to hair loss, scalp irritation, and allergic reactions. Formaldehyde released is a known carcinogen.",
        "research_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7068208/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Imidazolidinyl Urea",
        "aliases": ["imidazolidinyl urea", "imidurea", "germall 115"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Releases formaldehyde as a preservative. Common cause of allergic contact dermatitis and skin sensitization.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Diazolidinyl Urea",
        "aliases": ["diazolidinyl urea", "germall ii", "germall plus"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Formaldehyde-releasing preservative. Stronger releaser than imidazolidinyl urea. Linked to contact allergies and immune sensitization.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Quaternium-15",
        "aliases": ["quaternium-15", "dowicil 200", "dowicil 75", "methenamine chloroallyl chloride"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "One of the most potent formaldehyde-releasing preservatives. Most common cause of contact dermatitis in cosmetics.",
        "research_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5561297/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Bronopol",
        "aliases": ["bronopol", "2-bromo-2-nitropropane-1,3-diol", "onyxide 500", "myacide"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Releases formaldehyde and can form carcinogenic nitrosamines when combined with amines. Skin and eye irritant.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Sodium Hydroxymethylglycinate",
        "aliases": ["sodium hydroxymethylglycinate", "suttocide a", "glycine hydroxymethyl sodium salt"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Preservative that releases formaldehyde. Causes skin sensitization and allergic reactions, especially with repeated use.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Methenamine",
        "aliases": ["methenamine", "hexamethylenetetramine", "urotropin", "hexamine"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Releases formaldehyde upon contact with skin. Can cause contact allergies and sensitization.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "5-Bromo-5-Nitro-1,3-Dioxane",
        "aliases": ["5-bromo-5-nitro-1,3-dioxane", "bronidox l", "bronidox"],
        "category": "Formaldehyde Releaser",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "High",
        "description": "Formaldehyde-releasing biocide preservative. Can form nitrosamines (carcinogens) in the presence of secondary amines.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 3. PARABENS ───────────────────────────────────────────────────────
    {
        "name": "Methylparaben",
        "aliases": ["methylparaben", "methyl 4-hydroxybenzoate", "methyl paraben", "nipagin m"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Most commonly used paraben preservative. Detected in breast tumors, linked to endocrine disruption and estrogen mimicry. Suspected reproductive toxin.",
        "research_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1280330/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Ethylparaben",
        "aliases": ["ethylparaben", "ethyl 4-hydroxybenzoate", "ethyl paraben", "nipagin a"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben preservative linked to hormone disruption. Weak estrogenic activity; detected in human breast tissue.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Propylparaben",
        "aliases": ["propylparaben", "propyl 4-hydroxybenzoate", "propyl paraben", "nipasol m"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben with stronger estrogenic activity than methyl/ethylparaben. Linked to sperm count reduction and reproductive toxicity.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Butylparaben",
        "aliases": ["butylparaben", "butyl 4-hydroxybenzoate", "butyl paraben", "nipabutyl"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Strongest endocrine disruption among common parabens. Linked to breast cancer cell proliferation and reproductive harm.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Isobutylparaben",
        "aliases": ["isobutylparaben", "isobutyl 4-hydroxybenzoate", "isobutyl paraben"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben with endocrine-disrupting properties. Restricted or banned in some countries for use in baby products.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Isopropylparaben",
        "aliases": ["isopropylparaben", "isopropyl 4-hydroxybenzoate", "isopropyl paraben"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben preservative with hormonal activity. Restricted in the EU for some applications.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Benzylparaben",
        "aliases": ["benzylparaben", "benzyl 4-hydroxybenzoate", "benzyl paraben"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben with estrogenic properties. Can cause allergic contact dermatitis and skin sensitization.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Pentylparaben",
        "aliases": ["pentylparaben", "pentyl 4-hydroxybenzoate", "amylparaben"],
        "category": "Paraben",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Paraben preservative. Banned in the EU cosmetics regulation. Endocrine disruption risk.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 4. ISOTHIAZOLINONE PRESERVATIVES ─────────────────────────────────
    {
        "name": "Methylisothiazolinone",
        "aliases": ["methylisothiazolinone", "MIT", "MI", "2-methyl-4-isothiazolin-3-one", "neolone 950"],
        "category": "Isothiazolinone Preservative",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Powerful biocide preservative. Major cause of allergic contact dermatitis epidemic in Europe. EU banned it from leave-on cosmetics. Neurotoxic in vitro.",
        "research_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3863901/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Methylchloroisothiazolinone",
        "aliases": ["methylchloroisothiazolinone", "MCI", "CMIT", "chloromethylisothiazolinone", "kathon cg"],
        "category": "Isothiazolinone Preservative",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Always used in combination with MIT (Kathon CG blend). Known skin sensitizer; responsible for widespread contact allergy outbreaks.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Benzisothiazolinone",
        "aliases": ["benzisothiazolinone", "BIT", "1,2-benzisothiazolin-3-one", "proxel"],
        "category": "Isothiazolinone Preservative",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Industrial and cosmetic biocide. Skin sensitizer; can cause occupational contact allergies.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Octylisothiazolinone",
        "aliases": ["octylisothiazolinone", "OIT", "2-octyl-2H-isothiazol-3-one", "kathon 893"],
        "category": "Isothiazolinone Preservative",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Biocide used in paints and some cosmetics. Skin and aquatic toxin. Environmental concern.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 5. PHENOXYETHANOL ─────────────────────────────────────────────────
    {
        "name": "Phenoxyethanol",
        "aliases": ["phenoxyethanol", "2-phenoxyethanol", "ethylene glycol monophenyl ether", "phenoxetol"],
        "category": "Phenoxyethanol Group",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Common preservative. Can cause skin, eye, and lung irritation. France warned against use in products for babies under 3. Possible reproductive toxin at high doses.",
        "research_url": "https://www.ansm.sante.fr/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 6. BHT / BHA FAMILY ───────────────────────────────────────────────
    {
        "name": "BHT",
        "aliases": ["bht", "butylated hydroxytoluene", "2,6-di-tert-butyl-p-cresol", "butylhydroxytoluene"],
        "category": "BHT/BHA Family",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Synthetic antioxidant preservative. Possible endocrine disruptor. Some studies show tumor promotion in animals. Listed as possible carcinogen by some agencies.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "BHA",
        "aliases": ["bha", "butylated hydroxyanisole", "tert-butyl-4-methoxyphenol", "butylhydroxyanisole"],
        "category": "BHT/BHA Family",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Synthetic antioxidant. IARC classifies it as Group 2B possible carcinogen. Endocrine disruptor; EU restricts its use in cosmetics.",
        "research_url": "https://monographs.iarc.who.int/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Octadecyl Di-T-Butyl-4-Hydroxyhydrocinnamate",
        "aliases": ["octadecyl di-t-butyl-4-hydroxyhydrocinnamate", "irganox 1076", "stearyl 3-(3,5-di-tert-butyl-4-hydroxyphenyl)propionate"],
        "category": "BHT/BHA Family",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Synthetic antioxidant in the BHT family. Limited data on safety; classified as a potential skin sensitizer.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate",
        "aliases": ["pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate", "irganox 1010", "pentaerythritol tetrakis(3-(3,5-di-tert-butyl-4-hydroxyphenyl)propionate)"],
        "category": "BHT/BHA Family",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Hindered phenol antioxidant in BHT family. Minimal hazard data; used as plastic stabilizer; potential accumulation concern.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 7. PHTHALATES ─────────────────────────────────────────────────────
    {
        "name": "Diethyl Phthalate",
        "aliases": ["diethyl phthalate", "DEP", "ethyl phthalate", "phthalic acid diethyl ester"],
        "category": "Phthalate",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Most common phthalate in cosmetics (perfumes, nail polish). Endocrine disruptor; linked to reproductive harm and sperm damage. Often hidden under 'fragrance'.",
        "research_url": "https://www.ewg.org/skindeep/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Dibutyl Phthalate",
        "aliases": ["dibutyl phthalate", "DBP", "di-n-butyl phthalate", "phthalic acid dibutyl ester"],
        "category": "Phthalate",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Nail polish plasticizer. Classified as reproductive toxin (Category 1B) in EU. Banned in EU cosmetics. Strong endocrine disruptor.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Diethylhexyl Phthalate",
        "aliases": ["diethylhexyl phthalate", "DEHP", "bis(2-ethylhexyl) phthalate", "di(2-ethylhexyl) phthalate"],
        "category": "Phthalate",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Most widely studied phthalate. IARC Group 2B carcinogen. Disrupts male reproductive development; restricted globally.",
        "research_url": "https://monographs.iarc.who.int/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Benzyl Butyl Phthalate",
        "aliases": ["benzyl butyl phthalate", "BBP", "butyl benzyl phthalate", "santicizer 160"],
        "category": "Phthalate",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Endocrine disruptor linked to estrogenic activity. Banned in EU toys and childcare articles. Reproductive toxin.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Dimethyl Phthalate",
        "aliases": ["dimethyl phthalate", "DMP", "phthalic acid dimethyl ester", "methyl phthalate"],
        "category": "Phthalate",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Phthalate plasticizer and insect repellent. Less studied than others but shares class-level endocrine disruption concerns.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Diisononyl Phthalate",
        "aliases": ["diisononyl phthalate", "DINP", "phthalic acid diisononyl ester"],
        "category": "Phthalate",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Used as a replacement for DEHP. Animal studies show liver tumors. Endocrine disruption concerns; restricted for children's products in EU.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Diisodecyl Phthalate",
        "aliases": ["diisodecyl phthalate", "DIDP", "phthalic acid diisodecyl ester"],
        "category": "Phthalate",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Large-molecule phthalate with lower absorption rate but shares phthalate class concerns. Restricted in EU for children's products.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Di-n-octyl Phthalate",
        "aliases": ["di-n-octyl phthalate", "DNOP", "dioctyl phthalate", "DOP"],
        "category": "Phthalate",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Phthalate plasticizer. Liver and kidney toxicity in animal studies. Less estrogenic than DEHP but still a class concern.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 8. PFAS (FOREVER CHEMICALS) ───────────────────────────────────────
    {
        "name": "PTFE",
        "aliases": ["ptfe", "polytetrafluoroethylene", "teflon", "perfluorocarbon"],
        "category": "PFAS",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Synthetic fluoropolymer 'forever chemical'. Manufacturing process releases PFOA (carcinogen). Accumulates in environment and body; never breaks down.",
        "research_url": "https://www.epa.gov/pfas",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "PFOA",
        "aliases": ["pfoa", "perfluorooctanoic acid", "perfluorooctanoate", "c8"],
        "category": "PFAS",
        "danger_type": ["Carcinogen"],
        "severity": "High",
        "description": "IARC Group 2B carcinogen. Linked to kidney and testicular cancer. Persistent environmental pollutant; detected in human blood worldwide. Banned in EU.",
        "research_url": "https://monographs.iarc.who.int/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "PFOS",
        "aliases": ["pfos", "perfluorooctane sulfonate", "perfluorooctyl sulfonate"],
        "category": "PFAS",
        "danger_type": ["Carcinogen"],
        "severity": "High",
        "description": "Persistent PFAS chemical linked to cancer, thyroid disruption, and immune system effects. Listed under Stockholm Convention for global elimination.",
        "research_url": "https://www.epa.gov/pfas",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Perfluorodecalin",
        "aliases": ["perfluorodecalin", "perfluorodecahydronaphthalene", "flutec pp5"],
        "category": "PFAS",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Perfluorinated compound used in cosmetics for oxygen delivery claims. PFAS class chemical with bioaccumulation and persistence concerns.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Perfluorononyl Dimethicone",
        "aliases": ["perfluorononyl dimethicone", "fluorosilicone"],
        "category": "PFAS",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "PFAS-silicone hybrid used in cosmetics. Forever chemical that bioaccumulates; environmental and health hazard.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Polyperfluoromethylisopropyl Ether",
        "aliases": ["polyperfluoromethylisopropyl ether", "perfluoropolyether", "fomblin"],
        "category": "PFAS",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "High",
        "description": "Synthetic PFAS compound. Non-biodegradable; accumulates in environment. Belongs to PFAS class linked to cancer and immune suppression.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 9. ALUMINUM COMPOUNDS ─────────────────────────────────────────────
    {
        "name": "Aluminum Chlorohydrate",
        "aliases": ["aluminum chlorohydrate", "aluminium chlorohydrate", "ACH", "chlorohydrol"],
        "category": "Aluminum Compound",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Active ingredient in antiperspirants. Blocks sweat pores. Linked to breast cancer risk (near armpit application), neurotoxicity, and Alzheimer's disease debate.",
        "research_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2596440/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Aluminum Zirconium Compounds",
        "aliases": ["aluminum zirconium tetrachlorohydrex gly", "aluminum zirconium trichlorohydrex", "AZG"],
        "category": "Aluminum Compound",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Used in antiperspirants. Stronger pore-blocking than ACH alone. Same breast cancer proximity and neurotoxicity concerns as other aluminum salts.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Aluminum Hydroxide",
        "aliases": ["aluminum hydroxide", "aluminium hydroxide", "gibbsite", "al(oh)3"],
        "category": "Aluminum Compound",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Used as pH adjuster and opacifier. Aluminum accumulation in body is linked to neurological concerns with chronic exposure.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Magnesium Aluminum Silicate",
        "aliases": ["magnesium aluminum silicate", "MAS", "veegum", "montmorillonite"],
        "category": "Aluminum Compound",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Thickening clay mineral. Generally low hazard but may be contaminated with heavy metals. Not recommended for inhalation.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Aluminum Starch Octenylsuccinate",
        "aliases": ["aluminum starch octenylsuccinate", "dry flo plus", "dry flo af"],
        "category": "Aluminum Compound",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Aluminum-based starch used as absorbent in powders. Shares class concerns about aluminum bioaccumulation.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 10. ETHOXYLATED INGREDIENTS (PEG) ────────────────────────────────
    {
        "name": "PEG Compounds",
        "aliases": ["peg", "polyethylene glycol", "peg-4", "peg-6", "peg-8", "peg-12", "peg-20", "peg-32", "peg-40", "peg-60", "peg-80", "peg-100", "peg-150", "peg-200"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Ethoxylated compounds often contaminated with carcinogenic 1,4-dioxane and ethylene oxide during manufacturing. Enhances skin penetration of other harmful chemicals.",
        "research_url": "https://www.ewg.org/skindeep/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "PEG-40 Hydrogenated Castor Oil",
        "aliases": ["peg-40 hydrogenated castor oil", "cremophor rh 40", "kolliphor rh40"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Ethoxylated emulsifier. May be contaminated with 1,4-dioxane (carcinogen). Enhances absorption of other chemicals through skin.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "PEG-100 Stearate",
        "aliases": ["peg-100 stearate", "polyethylene glycol 100 stearate", "myrj 59"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Common emulsifier. Ethoxylation process can leave traces of ethylene oxide (carcinogen) and 1,4-dioxane.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "PEG-150 Distearate",
        "aliases": ["peg-150 distearate", "polyethylene glycol distearate"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Ethoxylated thickener. Same contamination concerns with 1,4-dioxane as other high-numbered PEG compounds.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Laureth Compounds",
        "aliases": ["laureth-2", "laureth-4", "laureth-7", "laureth-9", "laureth-10", "laureth-23", "sodium laureth sulfate", "SLES"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "Medium",
        "description": "Ethoxylated lauryl compounds. SLES is contaminated with 1,4-dioxane (carcinogen) during manufacturing. Skin irritant; strips natural oils.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Ceteareth Compounds",
        "aliases": ["ceteareth-2", "ceteareth-5", "ceteareth-10", "ceteareth-20", "ceteareth-25", "ceteareth-30"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Ethoxylated emulsifiers contaminated with 1,4-dioxane during manufacturing. Enhance penetration of other chemicals through skin barrier.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Trideceth-6",
        "aliases": ["trideceth-6", "tridecyl alcohol ethoxylate"],
        "category": "Ethoxylated Ingredient",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Ethoxylated tridecyl alcohol. May contain 1,4-dioxane from ethoxylation process.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 11. FRAGRANCE ─────────────────────────────────────────────────────
    {
        "name": "Fragrance",
        "aliases": ["fragrance", "parfum", "aroma", "perfume", "scent", "flavor", "fragrance complex"],
        "category": "Fragrance",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Catch-all term hiding 100s of undisclosed synthetic chemicals including phthalates, musks, and allergens. Most common cause of cosmetic contact allergy. No transparency required by law.",
        "research_url": "https://www.ewg.org/skindeep/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 12. ARTIFICIAL COLOURS ────────────────────────────────────────────
    {
        "name": "CI 42090 (Blue 1)",
        "aliases": ["ci 42090", "blue 1", "fd&c blue no. 1", "brilliant blue fcf", "acid blue 9"],
        "category": "Artificial Colour",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Synthetic coal tar dye. Linked to hyperactivity in children. Some animal studies show genotoxicity. Banned in some EU foods.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 19140 (Yellow 5)",
        "aliases": ["ci 19140", "yellow 5", "fd&c yellow no. 5", "tartrazine", "acid yellow 23"],
        "category": "Artificial Colour",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Azo dye linked to allergic reactions, asthma, and hyperactivity in children. Requires warning label in EU: 'may have an adverse effect on activity and attention in children'.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 15985 (Yellow 6)",
        "aliases": ["ci 15985", "yellow 6", "fd&c yellow no. 6", "sunset yellow fcf", "orange yellow s"],
        "category": "Artificial Colour",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Azo dye associated with hyperactivity, allergic reactions, and possible genotoxicity. Requires EU warning label for children's products.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 16035 (Red 40)",
        "aliases": ["ci 16035", "red 40", "fd&c red no. 40", "allura red ac", "food red 17"],
        "category": "Artificial Colour",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Most widely used red food and cosmetic dye. Linked to hyperactivity, allergic reactions, and possible genotoxicity in animal studies.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 17200 (Red 33)",
        "aliases": ["ci 17200", "red 33", "d&c red no. 33", "acid red 33", "dark red"],
        "category": "Artificial Colour",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Coal tar-derived azo dye. Not approved for use near eyes or on lips in the US. Potential carcinogen based on animal studies.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 45410 (Red 28)",
        "aliases": ["ci 45410", "red 28", "d&c red no. 28", "phloxine b", "acid red 92"],
        "category": "Artificial Colour",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Xanthene dye. Phototoxic and genotoxic in some studies. Not permitted for all cosmetic uses in all countries.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 73360 (Red 30)",
        "aliases": ["ci 73360", "red 30", "d&c red no. 30", "helindone pink"],
        "category": "Artificial Colour",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Vat dye used in cosmetics. Limited safety data; some sensitization potential. Not approved for all uses.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "CI 15850 (Red 6 / Red 7)",
        "aliases": ["ci 15850", "red 6", "red 7", "d&c red no. 6", "d&c red no. 7", "lithol rubin b", "lithol rubin bk"],
        "category": "Artificial Colour",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Azo dye used in lipsticks and nail polish. Some studies indicate genotoxicity. Not approved for use in all cosmetic categories.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },

    # ── 13. OTHER INGREDIENTS ─────────────────────────────────────────────
    {
        "name": "Triethanolamine",
        "aliases": ["triethanolamine", "TEA", "trolamine", "trihydroxytriethylamine", "2,2',2''-nitrilotriethanol"],
        "category": "Other",
        "danger_type": ["Carcinogen", "Irritant"],
        "severity": "Medium",
        "description": "pH adjuster and emulsifier. Can form carcinogenic nitrosamines when combined with nitrosating agents. Repeated skin exposure linked to liver and kidney toxicity in animals.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Isopropyl Myristate",
        "aliases": ["isopropyl myristate", "IPM", "tetradecanoic acid isopropyl ester", "crodamol ipm"],
        "category": "Other",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Emollient and penetration enhancer. Can clog pores and cause comedonal acne (blackheads/whiteheads). Also enhances absorption of other potentially harmful ingredients.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Isopropyl Palmitate",
        "aliases": ["isopropyl palmitate", "IPP", "hexadecanoic acid isopropyl ester", "crodamol ipp"],
        "category": "Other",
        "danger_type": ["Sensitive Skin Issue"],
        "severity": "Low",
        "description": "Emollient that readily penetrates skin. Highly comedogenic (pore-clogging). Can trigger acne and folliculitis, especially in acne-prone skin.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Iodopropynyl Butylcarbamate",
        "aliases": ["iodopropynyl butylcarbamate", "IPBC", "3-iodo-2-propynyl n-butylcarbamate", "glycacil"],
        "category": "Other",
        "danger_type": ["Irritant", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Potent biocide preservative. Restricted in EU (max 0.02% in rinse-off, not in lip/oral/spray products). Thyroid disruptor; banned in Canadian cosmetics.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Mineral Oil",
        "aliases": ["mineral oil", "paraffinum liquidum", "paraffin oil", "white mineral oil", "liquid paraffin", "petrolatum liquidum"],
        "category": "Other",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Petroleum-derived occlusive agent. Untreated/mildly treated grades classified as Group 1 carcinogens (IARC). Blocks pores; prevents skin from breathing. Often contaminated with PAHs (polycyclic aromatic hydrocarbons).",
        "research_url": "https://monographs.iarc.who.int/",
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
    {
        "name": "Petrolatum",
        "aliases": ["petrolatum", "petroleum jelly", "vaseline", "white petrolatum", "yellow petrolatum", "white soft paraffin"],
        "category": "Other",
        "danger_type": ["Carcinogen", "Sensitive Skin Issue"],
        "severity": "Medium",
        "description": "Petroleum byproduct used as occlusive moisturizer. Can be contaminated with PAHs (carcinogens) if not fully refined. EU requires proof of full refining process. Clogs pores.",
        "research_url": None,
        "added_date": datetime.utcnow(),
        "last_updated": datetime.utcnow(),
    },
]


async def seed():
    uri = os.getenv("MONGODB_URI")
    if not uri:
        print("❌ ERROR: MONGODB_URI not found in .env")
        return

    client = AsyncIOMotorClient(uri, maxPoolSize=5)
    db = client["toxiscan"]
    col = db["chemicals"]

    # Check existing count
    existing = await col.count_documents({})
    if existing > 0:
        print(f"⚠️  Collection already has {existing} documents.")
        confirm = input("Delete existing and re-seed? (yes/no): ").strip().lower()
        if confirm != "yes":
            print("Aborted.")
            client.close()
            return
        await col.delete_many({})
        print("🗑️  Existing chemicals deleted.")

    result = await col.insert_many(CHEMICALS)
    print(f"✅ Seeded {len(result.inserted_ids)} chemicals into 'toxiscan.chemicals'")

    # Create indexes for faster fuzzy search
    await col.create_index("name")
    await col.create_index("category")
    await col.create_index("severity")
    print("✅ Indexes created on: name, category, severity")

    # Summary by severity
    high = await col.count_documents({"severity": "High"})
    medium = await col.count_documents({"severity": "Medium"})
    low = await col.count_documents({"severity": "Low"})
    print(f"\n📊 Breakdown: High={high} | Medium={medium} | Low={low} | Total={high+medium+low}")

    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
